- name: Download {{ APP }} Component
  get_url:
    url: "{{URL}}"
    dest: /tmp/{{APP}}.zip

- name: Remove old content
  file:
    path: "{{EXTRACT_DIR}}"
    state: absent

- name: Create directory for {{ APP }} component
  file:
    path: "{{EXTRACT_DIR}}"
    state: directory

- name: Unarchive {{ APP}} Component
  ansible.builtin.unarchive:
    src: /tmp/{{APP}}.zip
    dest: "{{EXTRACT_DIR}}"
    remote_src: yes

- name: Move Htdocs Directory
  shell: mv /usr/share/nginx/html/static/* /usr/share/nginx/html/.
  when: APP == "frontend"
  # A shell command is decided to use over ansible module, Since we have static dir which is part of html directory causing the recursive problem for ansible module.
