- name: Download {{ APP }} Component
  get_url:
    url: "{{URL}}"
    dest: /tmp/{{APP}}.zip

- name: Remove old content
  file:
    path: "{{EXTRACT_DIR}}"
    state: absent

- name: Create directory for {{ APP }} component
  file:
    path: "{{EXTRACT_DIR}}"
    state: directory

- name: Unarchive {{ APP}} Component
  ansible.builtin.unarchive:
    src: /tmp/{{APP}}.zip
    dest: "{{EXTRACT_DIR}}"
    remote_src: yes

- name: Move Htdocs Directory
  copy:
    src: /usr/share/nginx/html/static/*
    dest: /usr/share/nginx/html/.
  when: APP == "frontend"

- name: Remove old htdocs
  file:
    path: /usr/share/nginx/html/static
    state: absent
  when: APP == "frontend"
