- name: Set Hostname for {{ COMPONENT }} Component
  ansible.builtin.shell: set-hostname {{ COMPONENT }}

- name: Disable Auto Shutdown for {{ COMPONENT }} Component
  ansible.builtin.shell: disable-auto-shutdown

- name: Add roboshop user
  ansible.builtin.user:
    name: roboshop
  when: APP == "catalogue" or APP == "user" or APP == "cart" or APP == "shipping" or APP == "payment"
  register: out

